# Generated by Django 5.1.7 on 2025-10-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_post_flag_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='flag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
